### ISSUE TITLE
Not working on Android?

### ISSUE THREAD

**Issue by OskarEichler** [FeatherJiang/react-native-video-cache-control#1]
Hey @FeatherJiang

Great job on this fork!! We are having an issue when calling isCached on Android:

![Screenshot 2022-11-23 at 13 54 14](https://user-images.githubusercontent.com/62393985/203480664-10c12100-004e-4832-90c2-41b6bfa98b30.jpg)

**Comment by FeatherJiang** [comment]
Please provide your package version at this lib

**Comment by OskarEichler** [comment]
@FeatherJiang 

react-native: 0.70.6
react-native-video-cache-control: 1.2.0
androidvideocache: 2.7.1

Got the same issue with convertToProxyURL

![Screenshot 2022-11-23 at 14 03 45](https://user-images.githubusercontent.com/62393985/203483104-904a6378-4e63-40bf-a417-d570b4a9d343.jpg)

**Comment by FeatherJiang** [comment]
Do you use this in readme?
-----------------------
Install on android
Edit your android/build.gradle file and add the following lines:

maven {
    url "$rootDir/../node_modules/react-native-video-cache-control/android/libs"
}
to your allprojects/repositories

**Comment by OskarEichler** [comment]
@FeatherJiang Yes I did - though I was switching over from the original library react-native-video-cache 

Everything was working there... is there a way to confirm that it's installed correctly?

Also synced Gradle and did ./gradlew clean still not working 😔

**Comment by FeatherJiang** [comment]
I will use your react native version create a example. 
Try to repeat the question.
Please wait my reply.

**Comment by FeatherJiang** [comment]
Please show your code.

**Comment by OskarEichler** [comment]
Can we do a Team Viewer session? That would be easiest so you can check it!

**Comment by FeatherJiang** [comment]
Probably not. I'm at work. 
Please give me your that part code. I will check it.

**Comment by FeatherJiang** [comment]
I use your react native version create a example.
It's work.

This is my code.
Can you try it or check it?

```javascript
import React, {useEffect, useState} from 'react';
import {View, Text, StyleSheet, TouchableOpacity} from 'react-native';
import convertToProxyURL, {
  clearCache,
  isCached,
} from 'react-native-video-cache-control';
import VideoPlayer from 'react-native-video-player';

const styles = StyleSheet.create({});

const array = [
  'https://prod-streaming-video-msn-com.akamaized.net/a8c412fa-f696-4ff2-9c76-e8ed9cdffe0f/604a87fc-e7bc-463e-8d56-cde7e661d690.mp4',
];

function App() {
  const [proxyUrl, setProxyUrl] = useState('');
  const [cached, setCached] = useState(false);

  useEffect(() => {
    const bool = isCached({
      url: array[0],
      headers: {
        referer: 'https://www.test.com',
      },
    });
    setCached(bool);
    const url = convertToProxyURL({
      url: array[0],
      headers: {
        referer: 'https://www.test.com',
      },
    });
    setProxyUrl(url);
  }, []);

  return (
    <View style={{flex: 1}}>
      <View style={[{width: 300, height: 300}]}>
        <VideoPlayer
          video={{
            uri: proxyUrl,
          }}
          videoWidth={300}
          videoHeight={300}
          autoplay
          thumbnail={{uri: 'https://i.picsum.photos/id/866/1600/900.jpg'}}
        />
      </View>
      <View style={[{flex: 1, justifyContent: 'center', alignItems: 'center'}]}>
        <TouchableOpacity
          onPress={() => {
            const bool = isCached({
              url: array[0],
              headers: {
                referer: 'https://www.test.com',
              },
            });
            setCached(bool);
          }}>
          <Text>{`url: ${array[0]}`}</Text>
          <Text>{`proxy: ${proxyUrl}`}</Text>
          <Text>{`cached: ${cached}`}</Text>
        </TouchableOpacity>
        <TouchableOpacity
          onPress={async () => {
            try {
              await clearCache(
                'https://prod-streaming-video-msn-com.akamaized.net/a8c412fa-f696-4ff2-9c76-e8ed9cdffe0f/604a87fc-e7bc-463e-8d56-cde7e661d690.mp4',
              );
            } catch (error) {
              console.log(error);
            }
          }}>
          <Text>Clear Cache</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

export default App;
```
my package.json
```json
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-vector-icons": "^9.2.0",
    "react-native-video": "^5.2.1",
    "react-native-video-cache-control": "^1.2.0",
    "react-native-video-player": "^0.14.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by OskarEichler** [comment]
@FeatherJiang Here is our code:
https://www.dropbox.com/s/khpwahqpmyy8uig/Screen%20Recording%202022-11-23%20at%2015.42.22.mov?dl=0

Please let me know if you see any difference - I'm also checking right now!

**Comment by OskarEichler** [comment]
Wow I just installed react-native-video-cache again and now have both libraries installed and now it is working!?

```
        maven { url "$rootDir/../node_modules/react-native-video-cache/android/libs" }
        maven { url "$rootDir/../node_modules/react-native-video-cache-control/android/libs" }
```

**Comment by OskarEichler** [comment]
Okay yeah so even when I just have react-native-video-cache-control in the gradle file it still works as long as I have react-native-video-cache installed.

`maven { url "$rootDir/../node_modules/react-native-video-cache-control/android/libs" }`

The moment I uninstall react-native-video-cache I'm getting the error again. Maybe it is linked to some old dependencies? Do you have an idea how to clean this up?

**Comment by FeatherJiang** [comment]
Try to remote node_moudle reinstall and clean android build cache and yarn start --reset

**Comment by OskarEichler** [comment]
Tried everything:

- Deleting node_modules + reinstalling
- Clear yarn cache
- Clean Android Build
- Rebuild
- Delete Gradle Cache
- Uninstall App
- Sync Gradle
- Invalidate Android Studio Caches

...nothing works! The moment react-native-video-cache is not in the package.json it gives the error. The funny thing is I even deleted the react-native-video-cache node_module but kept it in the package.json, and it still builds and runs fine. But the moment it's not inside the package.json I immediately am getting the error. Not sure what to do at this point other than leaving it in.

**Comment by samitha9125** [comment]
@FeatherJiang I can confirm this is happening regardless of what you do. Only solution is to install `react-native-cache` package as well.
