### ISSUE TITLE
verifyReleaseResources FAILED - Android

### ISSUE THREAD

**Issue by pmella16** [FeatherJiang/react-native-video-cache-control#3]
hi, i'm trying to use this library, in debug mode works fine, but when compile (./gradlew assembleRelease) to release mode i have this error, any help?

  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-video-cache-control": "^1.2.0"
  },

<img width="936" alt="image" src="https://github.com/FeatherJiang/react-native-video-cache-control/assets/19208317/d86c550d-9a31-4734-bbfa-e2043810897d">

**Comment by FeatherJiang** [comment]
I solved this problem, please update to 1.2.1
