### ISSUE TITLE
Whats the difference between this repo and the reference?

### ISSUE THREAD

**Issue by oshriza** [FeatherJiang/react-native-video-cache-control#4]
Hey,
thank you for maintaining such an important topic in react-native with videos.
Could you explain please the difference between this one and [this](https://github.com/zhigang1992/react-native-video-cache)?

Thanks :)

**Comment by FeatherJiang** [comment]
this repo add those feature:
1.add set http header
2.add `isCache` function
3.add `clearCache ` function
