### ISSUE TITLE
code not working in android

### ISSUE THREAD

**Issue by anushkasain** [FeatherJiang/react-native-video-cache-control#7]
Added below line in build.gradle

   allprojects {  // <- you should have added this
        repositories {
            maven {
                url "$rootDir/../node_modules/react-native-video-cache-control/android/libs"
            }
        }
    }

import convertToProxyURL from 'react-native-video-cache-control';

<Video
        ref={videoRef}
        source={{uri: convertToProxyURL("http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4")}}
        muted={false}
        volume={1.0}
        ignoreSilentSwitch={'ignore'}
        style={{ height: '99%', width: '100%', backgroundColor: 'black' }}
        paused={playerState === 'paused' || playerState === 'ended'}
        onLoad={handleLoad}
        onError={handleError}
        onEnd={handleEnd}
        onProgress={handleProgress}
        onTouchEnd={handleVideoTouch}
      />
      
      its throw error like:-
       
Error: Exception in HostFunction: com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `object', but had type `string'
       
**iOS woking fine**

@FeatherJiang ,  I have update wrong code(removed cache props from source prop) from  in above code.

when I removed "convertToProxyURL" then code is working fine.

but its working fine in IOS with "convertToProxyURL". Problem in only android

**Comment by FeatherJiang** [comment]
Please check your code about props type.

**Comment by anushkasain** [comment]
@FeatherJiang , I have update code in above comment, still I am getting issues in android.

**Comment by FeatherJiang** [comment]
This may be the problem,please update to 1.2.3 #8
