### ISSUE TITLE
Bug: Missing SLF4J dependency in release APK builds

### ISSUE THREAD

**Issue by str1ve21** [FeatherJiang/react-native-video-cache-control#8]
**Description**  
The issue occurs only in release APK builds. During local development (debug builds), everything works fine. However, in release builds, the app crashes due to a missing SLF4J dependency.

**Details**  
After investigating, I found that the issue is related to the SLF4J dependency not being included in the library. A similar problem was reported and resolved in [this issue](https://github.com/zhigang1992/react-native-video-cache/issues/75) for the `react-native-video-cache` library. The same solution should be applied to this library.

**Proposed Solution**  
The issue can be fixed by adding the following line to the `dependencies` block in `android/build.gradle`:  
```gradle
implementation 'org.slf4j:slf4j-api:2.0.9'
```

**Temporary Fix**  
I was able to resolve the issue in my project by applying a patch using the `patch-package` tool. However, it would be ideal if this fix were integrated directly into the library to avoid manual patches for every project using it.

**Steps to Reproduce**  
1. Build and run the app in dev/release mode.  
2. Install the generated APK on a device.  
3. The app crashes when trying to use the library.

**Environment**  
- react-native-video-cache-control: 1.2.2
- React Native: 0.72.12
- Android version: any

**References**  
- Similar issue in `react-native-video-cache`: [#75](https://github.com/zhigang1992/react-native-video-cache/issues/75)
- Sentry error: `RuntimeException com.facebook.react.bridge.JavaMethodWrapper in invoke`, `Could not invoke VideoCacheControl.convertAsync`, and then description: `ClassNotFoundException: org.slf4j.LoggerFactory`

Please consider integrating this fix into the library. Let me know if you need further information or assistance.

**Comment by FeatherJiang** [comment]
I have solved this problem, please update to 1.2.3.Thanks for your reminder.
